# Generated by Django 5.2.6 on 2025-09-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awarenessmap',
            name='extra_property_1',
        ),
        migrations.RemoveField(
            model_name='awarenessmap',
            name='extra_property_2',
        ),
        migrations.RemoveField(
            model_name='awarenessmap',
            name='property_1',
        ),
        migrations.RemoveField(
            model_name='awarenessmap',
            name='property_2',
        ),
        migrations.RemoveField(
            model_name='awarenessmap',
            name='property_3',
        ),
        migrations.RemoveField(
            model_name='awarenessmap',
            name='property_4',
        ),
        migrations.RemoveField(
            model_name='nightmaremap',
            name='extra_property_1',
        ),
        migrations.RemoveField(
            model_name='nightmaremap',
            name='extra_property_2',
        ),
        migrations.RemoveField(
            model_name='nightmaremap',
            name='property_1',
        ),
        migrations.RemoveField(
            model_name='nightmaremap',
            name='property_2',
        ),
        migrations.RemoveField(
            model_name='nightmaremap',
            name='property_3',
        ),
        migrations.RemoveField(
            model_name='nightmaremap',
            name='property_4',
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='extra_property_1_description',
            field=models.TextField(blank=True, verbose_name='Описание доп. свойства 1'),
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='extra_property_2_description',
            field=models.TextField(blank=True, verbose_name='Описание доп. свойства 2'),
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='property_1_condition',
            field=models.TextField(blank=True, verbose_name='Условие активации свойства 1'),
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='property_1_description',
            field=models.TextField(blank=True, verbose_name='Описание свойства 1'),
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='property_2_condition',
            field=models.TextField(blank=True, verbose_name='Условие активации свойства 2'),
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='property_2_description',
            field=models.TextField(blank=True, verbose_name='Описание свойства 2'),
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='property_3_condition',
            field=models.TextField(blank=True, verbose_name='Условие активации свойства 3'),
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='property_3_description',
            field=models.TextField(blank=True, verbose_name='Описание свойства 3'),
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='property_4_condition',
            field=models.TextField(blank=True, verbose_name='Условие активации свойства 4'),
        ),
        migrations.AddField(
            model_name='awarenessmap',
            name='property_4_description',
            field=models.TextField(blank=True, verbose_name='Описание свойства 4'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='extra_property_1_description',
            field=models.TextField(blank=True, verbose_name='Описание доп. свойства 1'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='extra_property_2_description',
            field=models.TextField(blank=True, verbose_name='Описание доп. свойства 2'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='property_1_condition',
            field=models.TextField(blank=True, verbose_name='Условие активации свойства 1'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='property_1_description',
            field=models.TextField(blank=True, verbose_name='Описание свойства 1'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='property_2_condition',
            field=models.TextField(blank=True, verbose_name='Условие активации свойства 2'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='property_2_description',
            field=models.TextField(blank=True, verbose_name='Описание свойства 2'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='property_3_condition',
            field=models.TextField(blank=True, verbose_name='Условие активации свойства 3'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='property_3_description',
            field=models.TextField(blank=True, verbose_name='Описание свойства 3'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='property_4_condition',
            field=models.TextField(blank=True, verbose_name='Условие активации свойства 4'),
        ),
        migrations.AddField(
            model_name='nightmaremap',
            name='property_4_description',
            field=models.TextField(blank=True, verbose_name='Описание свойства 4'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bonus_level',
            field=models.TextField(verbose_name='Дополнительные свойства'),
        ),
    ]
