# Generated by Django 5.2.6 on 2025-09-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_remove_awarenessmap_extra_property_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalrecipe',
            name='author_content_type',
        ),
        migrations.RemoveField(
            model_name='chemicalrecipe',
            name='author_object_id',
        ),
        migrations.RemoveField(
            model_name='mechanicalcompound',
            name='author_content_type',
        ),
        migrations.RemoveField(
            model_name='mechanicalcompound',
            name='author_object_id',
        ),
        migrations.AddField(
            model_name='chemicalrecipe',
            name='author_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_authored_as_doctor', to='clinica.doctor', verbose_name='Автор (врач)'),
        ),
        migrations.AddField(
            model_name='chemicalrecipe',
            name='author_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_authored_as_patient', to='clinica.patient', verbose_name='Автор (пациент)'),
        ),
        migrations.AddField(
            model_name='mechanicalcompound',
            name='author_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_authored_as_doctor', to='clinica.doctor', verbose_name='Автор (врач)'),
        ),
        migrations.AddField(
            model_name='mechanicalcompound',
            name='author_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_authored_as_patient', to='clinica.patient', verbose_name='Автор (пациент)'),
        ),
    ]
