# Generated by Django 5.2.6 on 2025-09-25 17:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_remove_chemicalrecipe_author_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='mentalstate',
            name='level',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)], verbose_name='Уровень ментального состояния'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mental_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='clinica.mentalstate', verbose_name='Ментальное состояние'),
        ),
    ]
