# Generated by Django 5.2.6 on 2025-09-26 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_patient_ser_alter_mentalstate_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalStatePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)], verbose_name='Уровень')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон ментального состояния',
                'verbose_name_plural': 'Шаблоны ментальных состояний',
                'ordering': ['level'],
            },
        ),
    ]
